# --- linuxserver/jellyfin
# --- ghcr.io/linuxserver/plex
# --- portainer/portainer

version: "3.8"
services:
  # Container management GUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
        - '8000:8000'
        - '9000:9000'
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/docker-configs/portainer:/data'
    restart: unless-stopped

  # Reverse proxy
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=nas.place
      - 'SUBDOMAINS=wildcard'
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - 'EMAIL=mrkfrancis8@gmail.com' #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
    volumes:
      - '/var/docker-configs/swag:/config'
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # Multimedia streaming platform
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - '/var/docker-configs/jellyfin:/config'
      - /mnt/tank/media/tv-series:/data/tv-series
      - /mnt/tank/media/movies:/data/movies
      - /mnt/tank/media/music/library:/data/music
    ports:
      - '8001:8096'
    restart: unless-stopped

  # Multimedia streaming platform
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    devices:
      - '/dev/dri:/dev/dri'
    volumes:
      - '/var/docker-configs/plex:/config'
      - /mnt/tank/media/tv-series:/tv
      - /mnt/tank/media/movies:/movies
      - /mnt/tank/media/music/library:/music
    restart: unless-stopped

  # TV show manager, which downloads missing episodes or an entire requested series
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - '/var/docker-configs/sonarr:/config'
      - /mnt/tank/media/tv-series:/tv #optional
      - '/mnt/tank/active-downloads:/downloads' #optional
    ports:
      - 8002:8989
    restart: unless-stopped

  # Torrent client
  transmission:
    # Pinned version due to issue with Ctrl+V
    # https://github.com/transmission/transmission/issues/5298
    image: lscr.io/linuxserver/transmission:4.0.1
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # - TRANSMISSION_WEB_HOME=/flood-for-transmission/ # Removed in v4
    volumes:
      - '/var/docker-configs/transmission:/config'
      - '/mnt/tank/active-downloads:/downloads'
    ports:
      - 8003:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # Torrent indexer proxy
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - '/var/docker-configs/jackett:/config'
      - '/mnt/tank/active-downloads:/downloads'
    ports:
      - 8004:9117
    restart: unless-stopped

  # Movie manager, which downloads requested movies  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - '/var/docker-configs/radarr:/config'
      - /mnt/tank/media/movies:/movies #optional
      - '/mnt/tank/active-downloads:/downloads' #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  # File browser
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - '/var/docker-configs/filebrowser/filebrowser.db:/database/filebrowser.db'
      - '/var/docker-configs/filebrowser/config:/config'
      - '/mnt/tank:/srv'
    ports:
      - 8006:80
    restart: unless-stopped

  # Ebook library manager
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - /var/docker-configs/calibre-web:/config
      - /mnt/tank/media/books:/books
    ports:
      - 8007:8083
    restart: unless-stopped
